# Generated by Django 2.2.3 on 2019-08-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='com_basic_info',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=50, unique=True)),
                ('begin_regit', models.DateTimeField(blank=True, null=True)),
                ('end_regit', models.DateTimeField(blank=True, null=True)),
                ('begin_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('num_stu', models.IntegerField(default=1)),
                ('need_full', models.BooleanField(default=0)),
                ('same_stu', models.BooleanField(default=0)),
                ('com_sort_num', models.IntegerField(default=0)),
                ('com_web', models.CharField(blank=True, max_length=225, null=True)),
                ('if_web', models.IntegerField(default=0)),
                ('num_teach', models.IntegerField(default=1)),
                ('com_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='com_group_basic_info',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=25, null=True)),
                ('group_num', models.IntegerField(default=1)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('else_info', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='com_need_info',
            fields=[
                ('com_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_num', models.BooleanField(default=0)),
                ('stu_name', models.BooleanField(default=0)),
                ('ID_number', models.BooleanField(default=0)),
                ('sex', models.BooleanField(default=0)),
                ('depart', models.BooleanField(default=0)),
                ('major', models.BooleanField(default=0)),
                ('grade', models.BooleanField(default=0)),
                ('stu_class', models.BooleanField(default=0)),
                ('email', models.BooleanField(default=0)),
                ('phone_num', models.BooleanField(default=0)),
                ('com_group', models.BooleanField(default=0)),
                ('group_name', models.BooleanField(default=0)),
                ('product_name', models.BooleanField(default=0)),
                ('tea_num', models.IntegerField(default=0)),
                ('bank_number', models.BooleanField(default=0)),
                ('else_info', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='com_sort_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_name', models.CharField(max_length=50)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='competition.com_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='temp_com_group_basic_info',
            fields=[
                ('temp_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=25, null=True)),
                ('group_num', models.IntegerField(default=1)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('else_info', models.TextField(blank=True, default='', null=True)),
                ('com_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.com_sort_info')),
                ('com_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='competition.com_basic_info')),
                ('group_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='competition.com_group_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='com_publish_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_announce', models.TextField(blank=True, null=True)),
                ('apply_step', models.TextField(blank=True, null=True)),
                ('com_attachment', models.FileField(blank=True, null=True, upload_to='com_attach')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='competition.com_basic_info')),
            ],
        ),
        migrations.AddField(
            model_name='com_group_basic_info',
            name='com_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.com_sort_info'),
        ),
        migrations.AddField(
            model_name='com_group_basic_info',
            name='com_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='competition.com_basic_info'),
        ),
    ]
