# Generated by Django 2.2.3 on 2019-08-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_info',
            fields=[
                ('class_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='depart_info',
            fields=[
                ('depart_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='grade_info',
            fields=[
                ('grade_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_login_info',
            fields=[
                ('account', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('psword', models.CharField(max_length=25)),
                ('have_login', models.CharField(default='0', max_length=5)),
                ('have_alter', models.CharField(default='0', max_length=5)),
                ('ip', models.CharField(max_length=25)),
                ('jurisdiction', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='major_info',
            fields=[
                ('major_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='all.depart_info')),
            ],
        ),
    ]
