# Generated by Django 2.2.4 on 2019-08-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_info',
            fields=[
                ('class_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='com_basic_info',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=50, unique=True)),
                ('begin_regit', models.DateTimeField(blank=True, null=True)),
                ('end_regit', models.DateTimeField(blank=True, null=True)),
                ('begin_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('num_stu', models.IntegerField(default=1)),
                ('need_full', models.BooleanField(default=0)),
                ('same_stu', models.BooleanField(default=0)),
                ('com_sort_num', models.IntegerField(default=0)),
                ('com_web', models.CharField(blank=True, max_length=225, null=True)),
                ('if_web', models.IntegerField(default=0)),
                ('num_teach', models.IntegerField(default=1)),
                ('com_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='com_group_basic_info',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=25, null=True)),
                ('group_num', models.IntegerField(default=1)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('else_info', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='com_need_info',
            fields=[
                ('com_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_num', models.BooleanField(default=0)),
                ('stu_name', models.BooleanField(default=0)),
                ('ID_number', models.BooleanField(default=0)),
                ('sex', models.BooleanField(default=0)),
                ('depart', models.BooleanField(default=0)),
                ('major', models.BooleanField(default=0)),
                ('grade', models.BooleanField(default=0)),
                ('stu_class', models.BooleanField(default=0)),
                ('email', models.BooleanField(default=0)),
                ('phone_num', models.BooleanField(default=0)),
                ('com_group', models.BooleanField(default=0)),
                ('group_name', models.BooleanField(default=0)),
                ('product_name', models.BooleanField(default=0)),
                ('tea_num', models.IntegerField(default=0)),
                ('bank_number', models.BooleanField(default=0)),
                ('else_info', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='depart_info',
            fields=[
                ('depart_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='grade_info',
            fields=[
                ('grade_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='major_info',
            fields=[
                ('major_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.depart_info')),
            ],
        ),
        migrations.CreateModel(
            name='profess_info',
            fields=[
                ('profess_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='stu_basic_info',
            fields=[
                ('stu_number', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=25)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=5)),
                ('ID_number', models.CharField(max_length=25)),
                ('bank_number', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('stu_card_photo', models.ImageField(blank=True, null=True, upload_to='stu_card_photo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.depart_info')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.grade_info')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.major_info')),
                ('stu_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.class_info')),
            ],
        ),
        migrations.CreateModel(
            name='user_login_info',
            fields=[
                ('account', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('psword', models.CharField(max_length=25)),
                ('have_login', models.CharField(default='0', max_length=5)),
                ('have_alter', models.CharField(default='0', max_length=5)),
                ('ip', models.CharField(max_length=25)),
                ('jurisdiction', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='teach_basic_info',
            fields=[
                ('tea_number', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('tea_name', models.CharField(max_length=25)),
                ('ID_number', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.depart_info')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.major_info')),
                ('profess', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.profess_info')),
            ],
        ),
        migrations.CreateModel(
            name='stu_fllow_com_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.com_basic_info')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.stu_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='com_teach_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.com_basic_info')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.com_group_basic_info')),
                ('teach_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.teach_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='com_stu_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=0)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.com_basic_info')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.com_group_basic_info')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.stu_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='com_sort_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_name', models.CharField(max_length=50)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.com_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='com_publish_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_announce', models.TextField(blank=True, null=True)),
                ('apply_step', models.TextField(blank=True, null=True)),
                ('com_attachment', models.FileField(blank=True, null=True, upload_to='com_attach')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.com_basic_info')),
            ],
        ),
        migrations.AddField(
            model_name='com_group_basic_info',
            name='com_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.com_sort_info'),
        ),
        migrations.AddField(
            model_name='com_group_basic_info',
            name='com_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='manager.com_basic_info'),
        ),
    ]
