# Generated by Django 2.2.3 on 2019-07-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_info',
            fields=[
                ('class_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='depart_info',
            fields=[
                ('depart_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='grade_info',
            fields=[
                ('grade_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='major_info',
            fields=[
                ('major_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='stu_basic_info',
            fields=[
                ('stu_number', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=25)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=5)),
                ('ID_number', models.CharField(max_length=25)),
                ('bank_number', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('stu_card_photo', models.ImageField(blank=True, null=True, upload_to='stu_card_photo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.depart_info')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.grade_info')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.major_info')),
                ('stu_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.class_info')),
            ],
        ),
        migrations.CreateModel(
            name='user_login_info',
            fields=[
                ('account', models.ForeignKey(default='123456', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manager.stu_basic_info')),
                ('psword', models.CharField(max_length=25)),
                ('ip', models.CharField(max_length=25)),
                ('jurisdiction', models.CharField(max_length=5)),
            ],
        ),
    ]
