# Generated by Django 2.2.3 on 2019-07-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login_info',
            name='account',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
