# Generated by Django 2.2.3 on 2019-08-05 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com_group_basic_info',
            name='com_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='manager.com_basic_info'),
        ),
        migrations.AlterField(
            model_name='com_group_basic_info',
            name='else_info',
            field=models.TextField(default=''),
        ),
    ]
