# Generated by Django 2.2.3 on 2019-08-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190805_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com_group_basic_info',
            name='else_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
