# Generated by Django 2.2.3 on 2019-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190720_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login_info',
            name='have_login',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
