# Generated by Django 2.2.3 on 2019-08-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190805_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com_teach_info',
            name='group_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='manager.com_group_basic_info'),
            preserve_default=False,
        ),
    ]
