# Generated by Django 2.2.3 on 2019-07-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_user_login_info_have_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login_info',
            name='have_alter',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
