# Generated by Django 2.2.3 on 2019-07-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_profess_info_teach_basic_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='teach_basic_info',
            name='department',
            field=models.ForeignKey(default='信息科学技术学院', on_delete=django.db.models.deletion.DO_NOTHING, to='manager.depart_info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teach_basic_info',
            name='major',
            field=models.ForeignKey(default='软件工程', on_delete=django.db.models.deletion.DO_NOTHING, to='manager.major_info'),
            preserve_default=False,
        ),
    ]
