# Generated by Django 2.2.3 on 2019-08-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all', '0001_initial'),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profess_info',
            fields=[
                ('profess_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='teach_basic_info',
            fields=[
                ('tea_number', models.CharField(default='0', max_length=25, primary_key=True, serialize=False)),
                ('tea_name', models.CharField(max_length=25)),
                ('ID_number', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='all.depart_info')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='all.major_info')),
                ('profess', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.profess_info')),
            ],
        ),
        migrations.CreateModel(
            name='temp_com_teach_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teach_basic_info')),
                ('temp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.temp_com_group_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='com_teach_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='competition.com_basic_info')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='competition.com_group_basic_info')),
                ('teach_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teach_basic_info')),
            ],
        ),
    ]
